### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by sakshib0811** [AmanSingh137/DSP_Calculator#1]
There are lots of changes required for styling this page

**Comment by AmanSingh137** [comment]
Go for it. Please make changes and give a PR.

**Comment by adesh8299** [comment]
hi,I would love to work on it.

**Comment by AmanSingh137** [comment]
Yeah you can go ahead @adesh8299

**Comment by adesh8299** [comment]
@AmanSingh137 i have raised my pr please review this.

**Comment by AmanSingh137** [comment]
@adesh8299 please fork the project again and try to make the new one responsive. Looking forward towards your valuable contribution.
